### ISSUE TITLE
Composer Provision

### ISSUE THREAD

**Issue by MGatner** [agungsugiarto/codeigniter4-authentication#13]
Hi! I wanted to point out to you, as a maintainer of a CodeIgniter 4 authentication module, that we have added a `provides` statement to help standardize authentication formats: https://codeigniter4.github.io/CodeIgniter4/extending/authentication.html

It is very loose at this point but even those simple recommendations and corresponding Composer line should help developers a lot.

**Comment by agungsugiarto** [comment]
Hello @MGatner, thank u for suggestion.

Can i suggest also, to update documentation with link pointing to packagist. example https://packagist.org/providers/codeigniter4/authentication-implementation

**Comment by agungsugiarto** [comment]
Here we go
![Screenshot (18)](https://user-images.githubusercontent.com/10989147/109095981-4fceb280-774f-11eb-8ff2-75d49bae4033.png)

**Comment by MGatner** [comment]
Well you added the provision without implementing the requirements, which is quite misleading. Please review the User Guide link, but basically you are missing:
* The function `user_id()` to return the unique identifier for a current user
* CodeIgniter Events for "login" and "logout"

Thank you for the Packagist link suggestion, that's a great idea! I just sent it over (and mentioned you).

One more thing while I'm here... I made some interfaces that my modules will use for identifying user data. The auto-discovery (https://github.com/tattersoftware/codeigniter4-users/blob/develop/src/UserProvider.php) checks for a few known modules and I would like to add yours. I can wrap them in an adapter and provide the methods, unless you would prefer to provide those natively? See `UserEntity` and `UserFactory` interfaces.

**Comment by agungsugiarto** [comment]
#16 i hope you're happy @MGatner in this pr is fully provide `codeigniter4/authentication-implementation` 😄 

About you're package `codeigniter4-users` you can wrap this the entitty reference is from interface https://github.com/agungsugiarto/codeigniter4-authentication/blob/master/src/Contracts/AuthenticatorInterface.php and implementation from https://github.com/agungsugiarto/codeigniter4-authentication/blob/master/src/Traits/AuthenticatableTrait.php

and the user factory from https://github.com/agungsugiarto/codeigniter4-authentication/blob/master/src/Contracts/UserProviderInterface.php implementation https://github.com/agungsugiarto/codeigniter4-authentication/blob/master/src/Traits/UserProviderTrait.php

**Comment by MGatner** [comment]
Thanks for the info, I will integrate that!

One mistake I noted inline on your PR but otherwise it looks great.

**Comment by agungsugiarto** [comment]
> Thanks for the info, I will integrate that!
> 
> One mistake I noted inline on your PR but otherwise it looks great.

thank u, already fix a248d264806b650c2396fefae46e0239b8c8eb40

**Comment by MGatner** [comment]
I've included your library, using the "Fluent" handle: https://github.com/tattersoftware/codeigniter4-users/commit/a7eba6508c95f6b464613696fb7590549811f7e5

This latest release includes two new extensions to the user interface, `HasGroup` and `HasPermission`, for modules that need those additional methods. If you end up implementing these in your library please let me know and I will add the additional interfaces to my wrapper. https://github.com/tattersoftware/codeigniter4-users/tree/develop/src/Interfaces

**Comment by agungsugiarto** [comment]
Thank u @MGatner, but i dont have plan to make authorization. Let community make authorization for this package.
