### ISSUE TITLE
Why is vendor namespace `Fluent`?

### ISSUE THREAD

**Issue by kenjis** [agungsugiarto/codeigniter4-authentication#25]
Fluent is used by this package:
https://packagist.org/packages/fluent/logger

Are you and the owner of the package the same vendor?

**Comment by agungsugiarto** [comment]
Iam just pick random word, i choose "Fluent" like nice to me. Nothing connection with first owner vendor. Its is will be future issue @kenjis ?

**Comment by kenjis** [comment]
@agungsugiarto You're using other's vendor namespace.
If the owner of `Fluent` provide a package wit the same classname which you are using,
they are conflicts.

Your package name is `agungsugiarto//codeigniter4-authentication`.
So you should use `Agungsugiarto`.

> The vendor name exists to prevent naming conflicts. For example, by including a vendor name both igorw and seldaek can have a library named json by naming their packages igorw/json and seldaek/json.
https://packagist.org/about?q=tiki-ongkir

**Comment by agungsugiarto** [comment]
Thank you @kenjis, for info. Since https://packagist.org/packages/fluent/logger is deprecated it will be fine.

**Comment by kenjis** [comment]
@agungsugiarto What do you mean *deprecated*?

And it is not the problem with the fluent/logger. You misuse the vendor namespace of theirs.
It is the same you use `Illuminate` as your namespace.

Could you fix the namespace?
If you fix it, I could use this without worry.
