### ISSUE TITLE
invalidchars filter dont work with remember login option

### ISSUE THREAD

**Issue by luciocodeigniter** [agungsugiarto/codeigniter4-authentication#30]
Hello Agung!

When I try to login enabling the remember login option and if I have invalidchars filter enabled, I get the following error:

CodeIgniter\Security\Exceptions\SecurityException #400
Invalid UTF-8 characters in cookie:  _ T  x  [͂LcKQr  & W V   = ) T   I 5 u  #
\F^0 z  ŕ   ܂ ~  碱  f] 5+TlJ y J/M=VlH  q        ɖ P K   1XYv z     :A  W!m  m   z  ղ;ӊ~y  2f￫\'   R    b    

Environment:

PHP 8.1.4
CI 4 Version: 4.1.9

Thanks.

**Comment by agungsugiarto** [comment]
Hello @luciocodeigniter, i'm can't reproduce this issue, can you share more detail ex log and configuration your application.

**Comment by luciocodeigniter** [comment]
Hi @agungsugiarto, of course you do. Apologies for the delay.

To reproduce the error, please have `Codeigniter version 4.1.9`, globally enable the 'invalidchars' filter and when logging in, choose the "Remember me" option.

app\Config\Filters.php

public $aliases = [
        'csrf'          => CSRF::class,
        'toolbar'       => DebugToolbar::class,
        'honeypot'      => Honeypot::class,
        `'invalidchars'  => InvalidChars::class, // That filter I mentioned`
        'secureheaders' => SecureHeaders::class,
         
       ///.....
];


/**
     * List of filter aliases that are always
     * applied before and after every request.
     *
     * @var array
     */
    public $globals = [
        'before' => [
            'honeypot',
            'csrf' => ['except' => 'radar-actions*'],
            'invalidchars', `//  when I enable this filter, the mentioned error with remember-me in the login form happens`
        ],
    ];

----------------------------------------------------------------------------------------------------
Logs:

CRITICAL - 2022-05-13 03:18:43 --> Invalid UTF-8 characters in cookie: ��y������Z�"�M�Ȩh[1C6w���1�)���#-:�ۃ�؛т��YE﹔�bSG߱
�W�	�ӌr���;����n-:@���Hrg��[t�a�Nb.��C�t����7ґz�Ix�ޝ��ڀZ7$[��
�Ǒ���h�Mk":`#��պ�I/�.!�/�
#0 C:\laragon\www\blitz\vendor\codeigniter4\framework\system\Filters\InvalidChars.php(99): CodeIgniter\Security\Exceptions\SecurityException::forInvalidUTF8Chars('cookie', '\xEE\x13\x84y\x9F\x9C\xCF\xD7\xEF\x18\xF8Z\x15\xF9"...')
#1 [internal function]: CodeIgniter\Filters\InvalidChars->checkEncoding('\xEE\x13\x84y\x9F\x9C\xCF\xD7\xEF\x18\xF8Z\x15\xF9"...')
#2 C:\laragon\www\blitz\vendor\codeigniter4\framework\system\Filters\InvalidChars.php(90): array_map(Array, Array)
#3 C:\laragon\www\blitz\vendor\codeigniter4\framework\system\Filters\InvalidChars.php(64): CodeIgniter\Filters\InvalidChars->checkEncoding(Array)
#4 C:\laragon\www\blitz\vendor\codeigniter4\framework\system\Filters\Filters.php(173): CodeIgniter\Filters\InvalidChars->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#5 C:\laragon\www\blitz\vendor\codeigniter4\framework\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('/', 'before')
#6 C:\laragon\www\blitz\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\blitz\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}

--------------------------------------------------------
Environment:

PHP 8.1.4
CI 4 Version: 4.1.9

Thanks.

**Comment by agungsugiarto** [comment]
@luciocodeigniter Thank u for reporting bug, already fixed in pr #36
