### ISSUE TITLE
InvalidArgumentException  when logging in

### ISSUE THREAD

**Issue by luciocodeigniter** [agungsugiarto/codeigniter4-authentication#31]
I'm getting the error below when trying to login:

InvalidArgumentException
Cache key contains reserved characters {}()/\@:

Below is an image of the error:
![Cache_key_contains_reserved_characters](https://user-images.githubusercontent.com/100212803/192102591-9d4f8e3d-6b41-41ff-8079-315482967730.png)

Setting my environment:

![AMBIENTE_ERRO_LOGIN](https://user-images.githubusercontent.com/100212803/192102778-fed00a29-3153-4fa5-a9b4-52cead881fd0.png)

**Comment by luciocodeigniter** [comment]
Thanks for the feedback!

Follow debug (dd) in the post and in the mentioned method:
![DEBUG_agungsugiarto](https://user-images.githubusercontent.com/100212803/194922555-1c8e814f-67d9-43e4-9f38-3256e44ec783.png)

**Comment by luciocodeigniter** [comment]
Just to complement,

I found a similar case on the web and the solution followed as follows.

Note: I applied what is mentioned in the following link and it seems to me that it fixed it.

Anyway, I'd like to know your opinion:

How it turned out:
```
// see: https://bytemeta.vip/repo/lonnieezell/myth-auth/issues/378
         return strtolower(Str::extractName($this->request->getPost('email'))) . '_' . str_replace("::", "", md5($this->request->getIPAddress()));
```

**Comment by agungsugiarto** [comment]
Fix in pr https://github.com/agungsugiarto/codeigniter4-authentication/pull/35
